#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "GLLE78",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-1"
config.compilers_tag = "20251015"
config.dtk_tag = "v1.4.1"
config.objdiff_tag = "v2.7.1"
config.sjiswrap_tag = "v1.2.0"
config.wibo_tag = "1.0.0-beta.5"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    f"--defsym BUILD_VERSION={version_num}",
    f"--defsym VERSION={config.version}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = 174

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    # "-W all",
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-fp_contract on",
    "-str reuse",
    "-multibyte",  # For Wii compilers, replace with `-enc SJIS`
    f"-i build/{config.version}/include",
    "-ir src/3rdParty/dolphin",
    "-ir include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C++/MSL_Common/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/Runtime/Inc",
    "-i src/3rdParty/PowerPC_EABI_Support/MetroTRK",
    "-i include/dolphin",
    "-i include",
    f"-DBUILD_VERSION={version_num}",
    f"-DVERSION_{config.version}",
    "-D__GEKKO__",
    "-O4,p",
]
cflags_bink_base = [
    "-O3",
    "-mcpu=750",
    "-fno-exceptions",
    "-Wno-inline",
    "-nostdinc",
    "-I src/3rdParty/dolphin",
    "-I include",
    "-I include/dolphin",
    "-D__GEKKO__",
    "-I src/3rdParty/bink/includes",
    "-I src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Include",
    "-G0",
]
cflags_noopt = cflags_base[:]

cflags_trk = [
    *cflags_base,
    "-use_lmw_stmw on",
    "-rostr",
    "-str reuse",
    "-common off",
    "-inline deferred,auto",
    "-char signed",
    "-sdata 0",
    "-sdata2 0",
]

# Dolphin library flags
cflags_dolphin = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-char unsigned",
    "-O4,p",
    "-sym on",
    "-inline auto",
    "-i include",
    f"-i build/{config.version}/include",
    "-ir src/3rdParty/dolphin",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/MSL/MSL_C++/MSL_Common/Include",
    "-i src/3rdParty/PowerPC_EABI_Support/Runtime/Inc",
    "-i src/3rdParty/PowerPC_EABI_Support/MetroTRK",
    "-i include/dolphin",
    f"-DVERSION={version_num}",
    "-D__GEKKO__",
    "-DSDK_REVISION=2",
]
cflags_noopt = cflags_dolphin[:]
cflags_noopt.remove("-O4,p")

cflags_rat_base = [
    *cflags_base,
    "-pool on",
    "-schedule on",
    "-fp fmadd",
    "-inline auto",
    "-use_lmw_stmw on",
    "-lang=c++",
    '-pragma "cpp_extensions on"',
    "-RTTI off",
    "-i src/Engine/includes",
    "-i src/LibGC/includes",
    "-i src/Rat/includes",
    "-O4,p",
    "-rostr",
]

if config.non_matching:
    cflags_rat_base.extend(["-DNONMATCHING_Z"])

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-use_lmw_stmw on",
    "-str reuse,pool,readonly",
    "-common off",
    "-inline auto",
    "-O4,p",
]

# REL flags
cflags_rel = [
    *cflags_base,
    "-sdata 0",
    "-sdata2 0",
]

config.linker_version = "GC/2.7"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_dolphin,
        "progress_category": "sdk",
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_rel,
        "progress_category": "game",
        "objects": objects,
    }


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    DolphinLib(
        "base",
        [
            Object(Matching, "3rdParty/dolphin/base/PPCArch.c"),
        ],
    ),
    DolphinLib(
        "os",
        [
            Object(Matching, "3rdParty/dolphin/os/__start.c"),
            Object(Matching, "3rdParty/dolphin/os/OS.c"),
            Object(Matching, "3rdParty/dolphin/os/OSAlarm.c"),
            Object(Matching, "3rdParty/dolphin/os/OSAlloc.c"),
            Object(Matching, "3rdParty/dolphin/os/OSArena.c"),
            Object(Matching, "3rdParty/dolphin/os/OSAudioSystem.c"),
            Object(Matching, "3rdParty/dolphin/os/OSCache.c"),
            Object(Matching, "3rdParty/dolphin/os/OSContext.c"),
            Object(Matching, "3rdParty/dolphin/os/OSError.c"),
            Object(Matching, "3rdParty/dolphin/os/OSExec.c"),
            Object(Matching, "3rdParty/dolphin/os/OSFont.c"),
            Object(Matching, "3rdParty/dolphin/os/OSInterrupt.c"),
            Object(Matching, "3rdParty/dolphin/os/OSLink.c"),
            Object(Matching, "3rdParty/dolphin/os/OSMemory.c"),
            Object(Matching, "3rdParty/dolphin/os/OSMutex.c"),
            Object(Matching, "3rdParty/dolphin/os/OSReboot.c"),
            Object(Matching, "3rdParty/dolphin/os/OSReset.c"),
            Object(Matching, "3rdParty/dolphin/os/OSResetSW.c"),
            Object(Matching, "3rdParty/dolphin/os/OSRtc.c"),
            Object(Matching, "3rdParty/dolphin/os/OSSync.c"),
            Object(Matching, "3rdParty/dolphin/os/OSThread.c"),
            Object(Matching, "3rdParty/dolphin/os/OSTime.c"),
            Object(Matching, "3rdParty/dolphin/os/OSFatal.c"), # --non-matching
            Object(Matching, "3rdParty/dolphin/os/__ppc_eabi_init.cpp"),
        ],
    ),
    {
        "lib": "exi",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_noopt,
        "progress_category": "sdk",
        "objects": [
            Object(Matching, "3rdParty/dolphin/exi/EXIBios.c", extra_cflags=["-O3,p"]),
            Object(Matching, "3rdParty/dolphin/exi/EXIUart.c", extra_cflags=["-O4,p"]),
        ],
    },
    DolphinLib(
        "si",
        [
            Object(Matching, "3rdParty/dolphin/si/SIBios.c"),
            Object(Matching, "3rdParty/dolphin/si/SISamplingRate.c"),
        ],
    ),
    DolphinLib(
        "db",
        [
            Object(Matching, "3rdParty/dolphin/db/db.c"),
        ],
    ),
    DolphinLib(
        "mtx",
        [
            Object(Matching, "3rdParty/dolphin/mtx/mtx.c", extra_cflags=["-char signed", "-O4,p"]),
            Object(Matching, "3rdParty/dolphin/mtx/mtx44.c", extra_cflags=["-char signed"]),
        ],
    ),
    DolphinLib(
        "dvd",
        [
            Object(Matching, "3rdParty/dolphin/dvd/dvdlow.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvdfs.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvd.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvdqueue.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvderror.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvdidutils.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/dvdFatal.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/dvd/fstload.c", extra_cflags=["-char signed"]),
        ],
    ),
    DolphinLib(
        "vi",
        [
            Object(Matching, "3rdParty/dolphin/vi/vi.c"),
        ],
    ),
    DolphinLib(
        "pad",
        [
            Object(Matching, "3rdParty/dolphin/pad/Padclamp.c"),
            Object(Matching, "3rdParty/dolphin/pad/Pad.c"),
        ],
    ),
    DolphinLib(
        "ai",
        [
            Object(Matching, "3rdParty/dolphin/ai/ai.c"),
        ],
    ),
    DolphinLib(
        "locale",
        [
            Object(NonMatching, "3rdParty/dolphin/locale.c"),
        ],
    ),
    DolphinLib(
        "ax",
        [
            Object(NonMatching, "3rdParty/dolphin/ax/AX.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXAlloc.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXAux.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXCL.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXOut.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXSPB.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXVPB.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXComp.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/DSPCode.c"),
            Object(NonMatching, "3rdParty/dolphin/ax/AXProf.c"),
        ],
    ),
    DolphinLib(
        "dsp",
        [
            Object(Matching, "3rdParty/dolphin/dsp/dsp.c"),
            Object(Matching, "3rdParty/dolphin/dsp/dsp_debug.c"),
            Object(Matching, "3rdParty/dolphin/dsp/dsp_task.c"),
        ],
    ),
    DolphinLib(
        "mix",
        [
            Object(Matching, "3rdParty/dolphin/mix/mix.c"),
        ],
    ),
    DolphinLib(
        "card",
        [
            Object(Matching, "3rdParty/dolphin/card/CARDBios.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDUnlock.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDRdwr.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDBlock.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDDir.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDCheck.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDMount.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDFormat.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDOpen.c", extra_cflags=["-char signed"]),
            Object(Matching, "3rdParty/dolphin/card/CARDCreate.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDRead.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDWrite.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDDelete.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDStat.c"),
            Object(Matching, "3rdParty/dolphin/card/CARDNet.c"),
        ],
    ),
    DolphinLib(
        "gx",
        [
            Object(Matching, "3rdParty/dolphin/gx/GXInit.c", extra_cflags=["-opt nopeephole"]),
            Object(Matching, "3rdParty/dolphin/gx/GXFifo.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXAttr.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXMisc.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXGeometry.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXFrameBuf.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXLight.c", extra_cflags=["-fp_contract off"]),
            Object(Matching, "3rdParty/dolphin/gx/GXTexture.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXBump.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXTev.c"),
            Object(NonMatching, "3rdParty/dolphin/gx/GXPixel.c"), # $VIOLET: non using the right sqrtf?
            Object(Matching, "3rdParty/dolphin/gx/GXDisplayList.c"),
            Object(Matching, "3rdParty/dolphin/gx/GXTransform.c", extra_cflags=["-fp_contract off"]),
            Object(Matching, "3rdParty/dolphin/gx/GXPerf.c"),
        ],
    ),
    DolphinLib(
        "gd",
        [
            Object(Matching, "3rdParty/dolphin/gd/GDBase.c"),
            Object(Matching, "3rdParty/dolphin/gd/GDGeometry.c"),
        ],
    ),
    DolphinLib(
        "ar",
        [
            Object(Matching, "3rdParty/dolphin/ar/ar.c"),
            Object(Matching, "3rdParty/dolphin/ar/arq.c"),
        ],
    ),
    DolphinLib(
        "texPalette",
        [
            Object(Matching, "3rdParty/dolphin/texPalette/texPalette.c"),
        ],
    ),
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.linker_version,
        "cflags": cflags_runtime,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/__mem.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/__va_arg.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/global_destructor_chain.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/CPlusLibPPC.cp"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/NMWException.cp", extra_cflags=["-Cpp_exceptions on"]),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/ptmf.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/runtime.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/__init_cpp_exceptions.cpp"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/Gecko_ExceptionPPC.cp"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/Runtime/Src/GCN_Mem_Alloc.c", extra_cflags=["-str reuse,nopool,readonly"]),
        ],
    },
    {
        "lib": "MSL_C",
        "mw_version": config.linker_version,
        "cflags": cflags_runtime,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/abort_exit.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/rand.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/alloc.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/errno.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/ansi_files.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Src/ansi_fp.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/arith.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/buffer_io.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/char_io.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/Src/critical_regions.gamecube.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/ctype.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/direct_io.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/file_io.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/FILE_POS.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/mbstring.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/mem.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/mem_funcs.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/misc_io.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/printf.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/scanf.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/float.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/signal.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/string.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/strtold.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/strtoul.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/wchar_io.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/qsort.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/Src/uart_console_io_gcn.c", extra_cflags=["-inline deferred,auto"]),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_acos.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_asin.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_atan2.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_exp.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_fmod.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_pow.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_rem_pio2.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_cos.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_rem_pio2.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_sin.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_tan.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_atan.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ceil.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_copysign.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_cos.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_floor.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_frexp.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ldexp.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_modf.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_sin.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_tan.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_acos.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_asin.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_atan2.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_exp.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_fmod.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_pow.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_sqrt.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/PPC_EABI/Src/math_ppc.c"),
            Object(Matching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_sqrt.c"),
            Object(NonMatching, "3rdParty/PowerPC_EABI_Support/MSL/MSL_C/MSL_Common/Src/extras.c"),
        ],
    },
    {
        "lib": "TRK_MINNOW_DOLPHIN",
        "mw_version": config.linker_version,
        "cflags": cflags_trk,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            # debugger
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/mainloop.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/nubevent.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/nubinit.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/msg.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/msgbuf.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/serpoll.c", extra_cflags=["-sdata 8"]),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/usr_put.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/dispatch.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/msghndlr.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/support.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/mutex_TRK.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/notify.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Processor/ppc/Generic/flush_cache.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/mem_TRK.c"),
            Object(NonMatching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Processor/ppc/Generic/targimpl.c"),
            Object(NonMatching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Processor/ppc/Export/targsupp.s"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Processor/ppc/Generic/mpc_7xx_603e.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Processor/ppc/Generic/exception.s"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Portable/main_TRK.c"),
            Object(NonMatching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk_glue.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/targcont.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/target_options.c"),
            Object(NonMatching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Export/mslsupp.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/debugger/embedded/MetroTRK/Os/dolphin/UDP_Stubs.c"),

            # gamedev
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/gamedev/cust_connection/cc/exi2/GCN/EXI2_DDH_GCN/main.c", extra_cflags=["-sdata 8"]),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/gamedev/cust_connection/utils/common/CircleBuffer.c"),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/gamedev/cust_connection/cc/exi2/GCN/EXI2_GDEV_GCN/main.c", extra_cflags=["-sdata 8"]),
            Object(Matching, "3rdParty/TRK_MINNOW_DOLPHIN/gamedev/cust_connection/utils/common/MWTrace.c"),
            Object(NonMatching, "3rdParty/TRK_MINNOW_DOLPHIN/gamedev/cust_connection/utils/gc/MWCriticalSection_gc.cpp", extra_cflags=["-lang=c"]),
        ],
    },
    {
        "lib": "amcstubs",
        "mw_version": config.linker_version,
        "cflags": cflags_dolphin,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            Object(Matching, "3rdParty/amcstubs/AmcExi2Stubs.c"),
        ],
    },
    {
        "lib": "odemuexi2",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_runtime,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            Object(Matching, "3rdParty/odemuexi2/DebuggerDriver.c", extra_cflags=["-inline deferred,auto"]),
        ],
    },
    {
        "lib": "odenotstub",
        "mw_version": config.linker_version,
        "cflags": cflags_dolphin,
        "progress_category": "sdk",
        "host": False,
        "objects": [
            Object(Matching, "3rdParty/odenotstub/odenotstub.c"),
        ],
    },
    {
        "lib": "Engine",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": ["engine", "rat"],  # str | List[str]
        "objects": [
            Object(NonMatching, "Engine/InGameDatas_Z.cpp"),
            Object(NonMatching, "Engine/ObjectBankManager_Z.cpp"),
            Object(NonMatching, "Engine/GameManager_Z.cpp"),
            Object(NonMatching, "Engine/Math_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjects_Z.cpp"),
            Object(NonMatching, "Engine/SuperSprayEle_Z.cpp"),
            Object(NonMatching, "Engine/GameSub_Z.cpp"),
            Object(NonMatching, "Engine/StreamFile_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/LodMove_Z.cpp"),
            Object(NonMatching, "Engine/LodAgent_Z.cpp"),
            Object(NonMatching, "Engine/CameraZoneLoad_Z.cpp"),
            Object(Matching,    "Engine/Txt_Z.cpp"),
            Object(Matching,    "Engine/PointsLoad_Z.cpp"),
            Object(NonMatching, "Engine/Menu3DLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/LodShadow_Z.cpp"),
            Object(NonMatching, "Engine/Surface_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollision_Z.cpp"),
            Object(NonMatching, "Engine/GameSubData_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolDraw_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesAgent_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZoneCapture_Z.cpp"),
            Object(Matching,    "Engine/VolatileMem_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGameClip_Z.cpp"),
            Object(NonMatching, "Engine/MeshLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraZoneDraw_Z.cpp"),
            Object(NonMatching, "Engine/Movie_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/Viewport_Z.cpp"),
            Object(NonMatching, "Engine/ABC_Agent.cpp"),
            Object(NonMatching, "Engine/WorldLightning_Z.cpp"),
            Object(NonMatching, "Engine/HFog_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMaterial_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMorph_Z.cpp"),
            Object(NonMatching, "Engine/Manipulator_Z.cpp"),
            Object(Matching,    "Engine/Parameters_Z.cpp"),
            Object(NonMatching, "Engine/MovieManipulator_Z.cpp"),
            Object(NonMatching, "Engine/Language_Z.cpp"),
            Object(NonMatching, "Engine/SkelLoad_Z.cpp"),
            Object(NonMatching, "Engine/Emiter_Z.cpp"),
            Object(NonMatching, "Engine/ErrorLanguage_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeLoad_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBounce_Z.cpp"),
            Object(NonMatching, "Engine/LodDraw_Z.cpp"),
            Object(NonMatching, "Engine/WorldAnim_Z.cpp"),
            Object(NonMatching, "Engine/LightDraw_Z.cpp"),
            Object(NonMatching, "Engine/Gaussian_Z.cpp"),
            Object(NonMatching, "Engine/EffectManager_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionCapsule_Z.cpp"),
            Object(NonMatching, "Engine/CameraUser_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesEle_Z.cpp"),
            Object(Matching,    "Engine/ConsoleCommand_Z.cpp"),
            Object(NonMatching, "Engine/Menu3D_Z.cpp"),
            Object(NonMatching, "Engine/Pack_Z.cpp"),
            Object(NonMatching, "Engine/Occluder_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/BaseObject_Z.cpp"),
            Object(NonMatching, "Engine/EmiterCollision_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerFloat_Z.cpp"),
            Object(NonMatching, "Engine/GraphVertex_Z.cpp"),
            Object(Matching,    "Engine/Memory_Z.cpp"),
            Object(NonMatching, "Engine/GameManipulators_Z.cpp"),
            Object(NonMatching, "Engine/Warp_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjectsManipulator_Z.cpp"),
            Object(NonMatching, "Engine/SplineLoad_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim_Z.cpp"),
            Object(NonMatching, "Engine/InGameDatasDraw_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionMovingSphere.cpp"),
            Object(NonMatching, "Engine/SkinDraw_Z.cpp"),
            Object(NonMatching, "Engine/OccluderDraw_Z.cpp"),
            Object(NonMatching, "Engine/SystemObject_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreak_Z.cpp"),
            Object(NonMatching, "Engine/OmniDraw_Z.cpp"),
            Object(NonMatching, "Engine/Frustrum_Z.cpp"),
            Object(NonMatching, "Engine/WorldCollision_Z.cpp"),
            Object(NonMatching, "Engine/LodLighting_Z.cpp"),
            Object(NonMatching, "Engine/MovingAgent_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionCapsule_Z.cpp"),
            Object(NonMatching, "Engine/GameStream_Z.cpp"),
            Object(Matching,    "Engine/Points_Z.cpp"),
            Object(NonMatching, "Engine/GameManagerRtc_Z.cpp"),
            Object(NonMatching, "Engine/SkinCollision_Z.cpp"),
            Object(NonMatching, "Engine/MatrixCache_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCache_Z.cpp"),
            Object(Matching,    "Engine/ABC_Category.cpp"),
            Object(NonMatching, "Engine/AnimatedMsgAgent_Z.cpp"),
            Object(NonMatching, "Engine/StreamAgent_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/SystemDatas_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesLoad_Z.cpp"),
            Object(NonMatching, "Engine/SkinAgent_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollision_Z.cpp"),
            Object(NonMatching, "Engine/CameraAgent_Z.cpp"),
            Object(NonMatching, "Engine/InputEngine_Z.cpp"),
            Object(NonMatching, "Engine/KSys_Z.cpp"),
            Object(NonMatching, "Engine/SplineDraw_Z.cpp"),
            Object(Matching,    "Engine/BitmapLoad_Z.cpp"),
            Object(NonMatching, "Engine/Game_Z.cpp"),
            Object(NonMatching, "Engine/ObjectThrow_Z.cpp"),
            Object(NonMatching, "Engine/Rtc_Z.cpp"),
            Object(NonMatching, "Engine/AnimationOmni_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerrVec3f_Z.cpp"),
            Object(Matching,    "Engine/ManipulatorManager_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGame_Z.cpp"),
            Object(NonMatching, "Engine/GraphLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngine_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/ABC_AgentReserve.cpp"),
            Object(NonMatching, "Engine/HFogDraw_Z.cpp"),
            Object(Matching,    "Engine/Name_Z.cpp"),
            Object(NonMatching, "Engine/LodCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/Sound_Z.cpp"),
            Object(NonMatching, "Engine/Sys_Z.cpp"),
            Object(Matching,    "Engine/UserDefine_Z.cpp"),
            Object(NonMatching, "Engine/MeshVolume_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/Renderer_Z.cpp",extra_cflags=["-O4,s"]),
            Object(NonMatching, "Engine/InGameObjectsDraw_Z.cpp"),
            Object(NonMatching, "Engine/ObjectGame_Z.cpp"),
            Object(NonMatching, "Engine/LightLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraOccluder_Z.cpp"),
            Object(NonMatching, "Engine/SequenceMixAnim_Z.cpp"),
            Object(NonMatching, "Engine/SubLevelVolumeAgent_Z.cpp"),
            Object(NonMatching, "Engine/Tree_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCollectable_Z.cpp"),
            Object(NonMatching, "Engine/AnimationCamera_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreakColl_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeCollision_Z.cpp"),
            Object(NonMatching, "Engine/PlayAnim_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerrVec2f_Z.cpp"),
            Object(NonMatching, "Engine/ObjectThrowColl_Z.cpp"),
            Object(NonMatching, "Engine/SubWorldLoad_Z.cpp"),
            Object(NonMatching, "Engine/GraphDraw_Z.cpp"),
            Object(NonMatching, "Engine/SeadIndex_Z.cpp"),
            Object(NonMatching, "Engine/UnSharedCollisionTool_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMove_Z.cpp"),
            Object(NonMatching, "Engine/Menu3DDraw_Z.cpp"),
            Object(NonMatching, "Engine/MeshAABB_Z.cpp"),
            Object(NonMatching, "Engine/MaterialAnimLoad_Z.cpp"),
            Object(Matching,    "Engine/Console_Z.cpp"),
            Object(NonMatching, "Engine/SelfRunning_Z.cpp"),
            Object(Matching,    "Engine/BitArray_Z.cpp"),
            Object(NonMatching, "Engine/CameraZone_Z.cpp"),
            Object(Matching,    "Engine/String_Z.cpp"),
            Object(NonMatching, "Engine/StreamManager_Z.cpp"),
            Object(NonMatching, "Engine/GameManagerCmd_Z.cpp"),
            Object(NonMatching, "Engine/Animation_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCling_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerRot_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreakCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/ClassManager_Z.cpp"),
            Object(NonMatching, "Engine/Collision_Z.cpp"),
            Object(NonMatching, "Engine/BoneNode_Z.cpp"),
            Object(NonMatching, "Engine/Node_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollVol_Z.cpp"),
            Object(NonMatching, "Engine/Camera_Z.cpp"),
            Object(NonMatching, "Engine/FlareDraw_Z.cpp"),
            Object(NonMatching, "Engine/ResourceObject_Z.cpp"),
            Object(NonMatching, "Engine/BigFileManager_Z.cpp"),
            Object(NonMatching, "Engine/SkinCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/AStar_Z.cpp"),
            Object(NonMatching, "Engine/Ghost_Z.cpp"),
            Object(NonMatching, "Engine/AnimFrameLoad_Z.cpp"),
            Object(NonMatching, "Engine/AnimationLoad_Z.cpp"),
            Object(NonMatching, "Engine/RendererPrimitiveBuffers_Z.cpp"),
            Object(NonMatching, "Engine/WaterHeightmap_Z.cpp"),
            Object(NonMatching, "Engine/Light_Z.cpp"),
            Object(NonMatching, "Engine/AnimFrame_Z.cpp"),
            Object(NonMatching, "Engine/SeadHandle_Z.cpp"),
            Object(NonMatching, "Engine/Menu_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionSphere.cpp"),
            Object(NonMatching, "Engine/SkelCollision_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolCollision_Z.cpp"),
            Object(NonMatching, "Engine/SubWorld_Z.cpp"),
            Object(NonMatching, "Engine/Lod_Z.cpp"),
            Object(NonMatching, "Engine/MeshDraw_Z.cpp"),
            Object(NonMatching, "Engine/InGameDatasLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMove_Z.cpp"),
            Object(NonMatching, "Engine/RotShape_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim1_Z.cpp"),
            Object(NonMatching, "Engine/RtcAgent_Z.cpp"),
            Object(NonMatching, "Engine/OccluderCollision_Z.cpp"),
            Object(NonMatching, "Engine/File_Z.cpp"),
            Object(NonMatching, "Engine/SkinLoad_Z.cpp"),
            Object(NonMatching, "Engine/MaterialAnim_Z.cpp"),
            Object(NonMatching, "Engine/Flare_Z.cpp"),
            Object(NonMatching, "Engine/VehiculeMove_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeDraw_Z.cpp"),
            Object(NonMatching, "Engine/Bitmap_Z.cpp", extra_cflags=["-O4,s"]),
            Object(NonMatching, "Engine/AnimatedAgent_Z.cpp"),
            Object(NonMatching, "Engine/ABC_ScriptManager.cpp"),
            Object(NonMatching, "Engine/LodCollisions_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceDraw_Z.cpp"),
            Object(NonMatching, "Engine/Error_Z.cpp"),
            Object(Matching,    "Engine/ClassNameResManager_Z.cpp"),
            Object(NonMatching, "Engine/SoundManager_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManager_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjectsLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/PopupMenu_Z.cpp"),
            Object(NonMatching, "Engine/SequenceAnim_Z.cpp"),
            Object(NonMatching, "Engine/WorldDraw_Z.cpp"),
            Object(NonMatching, "Engine/LodLoad_Z.cpp"),
            Object(NonMatching, "Engine/Menu2D_Z.cpp"),
            Object(NonMatching, "Engine/Handle_Z.cpp"),
            Object(NonMatching, "Engine/GameRtc_Z.cpp"),
            Object(NonMatching, "Engine/EmiterDraw_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManagerSkel_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZoneColl_Z.cpp"),
            Object(NonMatching, "Engine/Breakable_Z.cpp"),
            Object(NonMatching, "Engine/Material_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGameSkel_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim2_Z.cpp"),
            Object(NonMatching, "Engine/Agent_Z.cpp"),
            Object(NonMatching, "Engine/RtcAnimationNode_Z.cpp"),
            Object(NonMatching, "Engine/WorldLoad_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolLoad_Z.cpp"),
            Object(NonMatching, "Engine/GameObj_Z.cpp"),
            Object(NonMatching, "Engine/Graph_Z.cpp"),
            Object(NonMatching, "Engine/Skin_Z.cpp"),
            Object(NonMatching, "Engine/InputAction_Z.cpp"),
            Object(NonMatching, "Engine/S_MALLOC.cpp"),
            Object(NonMatching, "Engine/SkinCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/World_Z.cpp"),
            Object(NonMatching, "Engine/MaterialObj_Z.cpp"),
            Object(NonMatching, "Engine/MaterialManager_Z.cpp"),
            Object(NonMatching, "Engine/TriangleCache_Z.cpp"),
            Object(Matching,    "Engine/Random_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceLoad_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/GraphLevel_Z.cpp"),
            Object(NonMatching, "Engine/SplineZoneLoad_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerLoad_Z.cpp"),
            Object(NonMatching, "Engine/Main_Z.cpp"),
            Object(Matching,    "Engine/Object_Z.cpp"),
            Object(NonMatching, "Engine/Menu2DDraw_Z.cpp"),
            Object(NonMatching, "Engine/WarpLoad_Z.cpp"),
            Object(NonMatching, "Engine/ConsoleInterp_Z.cpp"),
            Object(NonMatching, "Engine/RtcLoad_Z.cpp"),
            Object(NonMatching, "Engine/SuperSpray_Z.cpp"),
            Object(NonMatching, "Engine/NetManager_Virtual_Z.cpp"),
            Object(NonMatching, "Engine/OccludedSeadHandle_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZone_Z.cpp"),
            Object(NonMatching, "Engine/ObjectCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/ABC_AgentMessage.cpp"),
            Object(NonMatching, "Engine/Fonts_Z.cpp"),
            Object(NonMatching, "Engine/PlayParticles_Z.cpp"),
            Object(NonMatching, "Engine/NetManager_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMesh_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVol_Z.cpp"),
            Object(NonMatching, "Engine/LodCollision_Z.cpp"),
            Object(NonMatching, "Engine/RtcPlayer_Z.cpp"),
            Object(NonMatching, "Engine/ABC_Behavior.cpp"),
            Object(NonMatching, "Engine/UnPack_Z.cpp"),
            Object(NonMatching, "Engine/CameraStream_Z.cpp"),
            Object(NonMatching, "Engine/DebugTools_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCling_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerU32_Z.cpp"),
            Object(NonMatching, "Engine/HFogLoad_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerHdl_Z.cpp"),
            Object(NonMatching, "Engine/NodeLoad_Z.cpp"),
            Object(Matching,    "Engine/MaterialLoad_Z.cpp"),
            Object(NonMatching, "Engine/SplineZoneDraw_Z.cpp"),
            Object(NonMatching, "Engine/CollisionTool_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerVec4f_Z.cpp"),
            Object(NonMatching, "Engine/UnSharedObjectCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManagerMes_Z.cpp"),
            Object(NonMatching, "Engine/GameAgent_Z.cpp"),
            Object(NonMatching, "Engine/AnimMessage_Z.cpp"),
            Object(NonMatching, "Engine/Omni_Z.cpp"),
            Object(NonMatching, "Engine/LodCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/ABC_ScriptManagerReserve_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/LodDynAgent_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCarrying_Z.cpp"),
            Object(NonMatching, "Engine/Particles_Z.cpp"),
            Object(NonMatching, "Engine/AnimationNode_Z.cpp"),
            Object(NonMatching, "Engine/Throwable_Z.cpp"),
            Object(NonMatching, "Engine/FontsDraw_Z.cpp"),
            Object(NonMatching, "Engine/Menu2DLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/NetDataSet_Z.cpp"),
            Object(NonMatching, "Engine/Mesh_Z.cpp"),
            Object(NonMatching, "Engine/CameraDraw_Z.cpp"),
            Object(NonMatching, "Engine/Spline_Z.cpp"),
            Object(NonMatching, "Engine/ConsoleMessage_Z.cpp"),
            Object(NonMatching, "Engine/Skel_Z.cpp"),
            Object(Matching,    "Engine/MeshMorph_Z.cpp"),
            Object(NonMatching, "Engine/SplineZone_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesDraw_Z.cpp"),
            Object(NonMatching, "Engine/VolumeAgent_Z.cpp"),
        ],
    },
    {
        "lib": "LibGC",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": ["libgc", "rat"],  # str | List[str]
        "objects": [
            Object(NonMatching, "LibGC/Streaming_Z.cpp"),
            Object(NonMatching, "LibGC/MathTools_Z.cpp"),
            Object(Matching,    "LibGC/LowMemory_Z.cpp"),
            Object(NonMatching, "LibGC/ARAM_Z.cpp"),
            Object(Matching,    "LibGC/Assert_Z.cpp"),
            Object(Matching,    "LibGC/String_Z.c"),
            Object(Matching,    "LibGC/Timer_Z.cpp"),
            Object(NonMatching, "LibGC/TextureManager_Z.cpp"),
            Object(NonMatching, "LibGC/DisplayList_Z.cpp"),
            Object(NonMatching, "LibGC/MeshGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsoleSystem_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGC_Z.cpp"),
            Object(NonMatching, "LibGC/SystemObjectGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer3D_Z.cpp"),
            Object(NonMatching, "LibGC/GCMovieManipulator_Z.cpp"),
            Object(NonMatching, "LibGC/SkinGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/SkelGC_Z.cpp"),
            Object(NonMatching, "LibGC/FlareGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCSound_Z.cpp"),
            Object(NonMatching, "LibGC/InGameObjectsGC_Z.cpp"),
            Object(NonMatching, "LibGC/WarpGC_Z.cpp"),
            Object(NonMatching, "LibGC/RotShapeGC_Z.cpp"),
            Object(NonMatching, "LibGC/ParticlesGC_Z.cpp"),
            Object(NonMatching, "LibGC/RotShapeGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCMcManager_Z.cpp"),
            Object(NonMatching, "LibGC/FlareGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCRendererTransp_Z.cpp"),
            Object(NonMatching, "LibGC/GCFile_Z.cpp"),
            Object(NonMatching, "LibGC/MaterialGC_Z.cpp"),
            Object(NonMatching, "LibGC/LodGC_Z.cpp"),
            Object(NonMatching, "LibGC/MathGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCDrawString.cpp"),
            Object(NonMatching, "LibGC/GCRendererLighting_Z.cpp"),
            Object(NonMatching, "LibGC/LodGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/ParticlesGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCFrustrum_Z.cpp"),
            Object(NonMatching, "LibGC/GCStreamManager_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundManager_Z.cpp"),
            Object(NonMatching, "LibGC/MeshGC_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCRendererDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCSndStream_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsole_Z.cpp"),
            Object(NonMatching, "LibGC/WarpGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundStreaming_Z.cpp"),
            Object(NonMatching, "LibGC/SkinGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCInput_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundBF.cpp"),
            Object(NonMatching, "LibGC/GCMovie_Z.cpp"),
            Object(NonMatching, "LibGC/GCMain_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsoleFolder_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer2D_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGCCache_Z.cpp"),
            Object(NonMatching, "LibGC/wiitextures.c"),
            Object(Matching,    "LibGC/LowLevelTools_Z.cpp"),
        ],
    },
    {
        "lib": "Game",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": ["game", "rat"],  # str | List[str]
        "objects": [
            Object(NonMatching, "Rat/Mission_Heist.cpp"),
            Object(NonMatching, "Rat/Mission_LinguiniMaking.cpp"),
            Object(NonMatching, "Rat/MenuManager_G.cpp"),
            Object(NonMatching, "Rat/CameraGame_G.cpp"),
            Object(NonMatching, "Rat/IsToBePlayed.cpp"),
            Object(NonMatching, "Rat/CreatureDeaths.cpp"),
            Object(NonMatching, "Rat/CreaturesBallMoveStates_G.cpp"),
            Object(NonMatching, "Rat/DummyGen.cpp"),
            Object(NonMatching, "Rat/CreatureFightStates_G.cpp"),
            Object(NonMatching, "Rat/BriefInfo.cpp"),
            Object(NonMatching, "Rat/Mission_Dream.cpp"),
            Object(NonMatching, "Rat/Mission_CookingPlateInterface.cpp"),
            Object(NonMatching, "Rat/PlayerMove_G.cpp"),
            Object(NonMatching, "Rat/Menu3DScenery.cpp"),
            Object(NonMatching, "Rat/VolumeDelayedStart_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Fish.cpp"),
            Object(NonMatching, "Rat/LogicAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_CollectTrigger.cpp"),
            Object(NonMatching, "Rat/GameMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureImpactStates_G.cpp"),
            Object(NonMatching, "Rat/IT_CarryingMove.cpp"),
            Object(NonMatching, "Rat/CharsData_G.cpp"),
            Object(NonMatching, "Rat/LoadingDraw_G.cpp"),
            Object(NonMatching, "Rat/IT_DYNOBJMove_G.cpp"),
            Object(NonMatching, "Rat/CreaturesWaitStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Wash.cpp"),
            Object(NonMatching, "Rat/FriendsMove_G.cpp"),
            Object(NonMatching, "Rat/InGameSounds_G.cpp"),
            Object(NonMatching, "Rat/CreaturesSwim_G.cpp"),
            Object(NonMatching, "Rat/Heros_G.cpp"),
            Object(NonMatching, "Rat/CreaturesPoleStates_G.cpp"),
            Object(NonMatching, "Rat/Shop.cpp"),
            Object(NonMatching, "Rat/ActionHelper_G.cpp"),
            Object(NonMatching, "Rat/CreaturesBoneManip.cpp"),
            Object(NonMatching, "Rat/InGameCreatures_G.cpp"),
            Object(NonMatching, "Rat/ObjectAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuKeys.cpp"),
            Object(NonMatching, "Rat/StreamGameAgent_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_Extras.cpp"),
            Object(NonMatching, "Rat/Mission_Goto.cpp"),
            Object(NonMatching, "Rat/IT_BallWalk_G.cpp"),
            Object(NonMatching, "Rat/BaseInGame3D.cpp"),
            Object(NonMatching, "Rat/ItemMgr_G.cpp"),
            Object(NonMatching, "Rat/PhysicObj_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayerPages_G.cpp"),
            Object(NonMatching, "Rat/CreaturesStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_CrepeInterface.cpp"),
            Object(NonMatching, "Rat/Frame_G.cpp"),
            Object(NonMatching, "Rat/CreatureStatic.cpp"),
            Object(NonMatching, "Rat/LiquidFlow_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Collect.cpp"),
            Object(NonMatching, "Rat/MissionTemplate_G.cpp"),
            Object(NonMatching, "Rat/CreatureGlissade.cpp"),
            Object(NonMatching, "Rat/Game_SoundMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureSkid.cpp"),
            Object(NonMatching, "Rat/Mission_CuttingPotatoes.cpp"),
            Object(NonMatching, "Rat/CreatureControlPanel.cpp"),
            Object(NonMatching, "Rat/CreaturesPushButtonStates_G.cpp"),
            Object(NonMatching, "Rat/CreatureRat_G.cpp"),
            Object(NonMatching, "Rat/EvenementVolAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_ControlPanel.cpp"),
            Object(NonMatching, "Rat/MenuLogicAgent_G.cpp"),
            Object(NonMatching, "Rat/GusteauMove.cpp"),
            Object(NonMatching, "Rat/VibrationManager_G.cpp"),
            Object(NonMatching, "Rat/CameraAgent_G.cpp"),
            Object(NonMatching, "Rat/CreatureSemaphore.cpp"),
            Object(NonMatching, "Rat/IT_Switch.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupInterfaceYesNo.cpp"),
            Object(NonMatching, "Rat/Mission_Colony.cpp"),
            Object(NonMatching, "Rat/Mission_WireConnect.cpp"),
            Object(NonMatching, "Rat/CreatureBumper.cpp"),
            Object(NonMatching, "Rat/Mission_LinguiniMakingInterface.cpp"),
            Object(NonMatching, "Rat/ScriptExternalCommands_G.cpp"),
            Object(NonMatching, "Rat/TextGameDraw_G.cpp"),
            Object(NonMatching, "Rat/FlyUpVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/IT_FishMove.cpp"),
            Object(NonMatching, "Rat/LevelManipulator_G.cpp"),
            Object(NonMatching, "Rat/CameraEdited.cpp"),
            Object(NonMatching, "Rat/Smell_G.cpp"),
            Object(NonMatching, "Rat/PhysicColl_G.cpp"),
            Object(NonMatching, "Rat/EnemyGenerator_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingLinguiniInterface.cpp"),
            Object(NonMatching, "Rat/Config_G.cpp"),
            Object(NonMatching, "Rat/BaseInGameDatas_G.cpp"),
            Object(NonMatching, "Rat/CreaturePST_TOOLS_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayer_G.cpp"),
            Object(Matching, "Rat/ResName.cpp"),
            Object(NonMatching, "Rat/Dialogs_LoadSave.cpp"),
            Object(NonMatching, "Rat/LightVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_MiniGame.cpp"),
            Object(NonMatching, "Rat/CreaturesManager_G.cpp"),
            Object(NonMatching, "Rat/RtcScriptAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_WashInterface.cpp"),
            Object(NonMatching, "Rat/CreatureFishing.cpp"),
            Object(NonMatching, "Rat/IT_Fish_G.cpp"),
            Object(NonMatching, "Rat/MultiMapLevel.cpp"),
            Object(NonMatching, "Rat/GuardAgent_G.cpp"),
            Object(NonMatching, "Rat/DialogGroup_G.cpp"),
            Object(NonMatching, "Rat/WanderingPath_G.cpp"),
            Object(NonMatching, "Rat/GangAgent_G.cpp"),
            Object(NonMatching, "Rat/FootPrints_G.cpp"),
            Object(NonMatching, "Rat/AutoCompletion_G.cpp"),
            Object(NonMatching, "Rat/ThrownMove_G.cpp"),
            Object(NonMatching, "Rat/Mission_MutliTemplate_G.cpp"),
            Object(NonMatching, "Rat/Mission_WireConnectInterface.cpp"),
            Object(NonMatching, "Rat/Mission_CuttingPotatoesInterface.cpp"),
            Object(NonMatching, "Rat/ChangeLevelVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Friends_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_System.cpp"),
            Object(NonMatching, "Rat/ScriptExternals_G.cpp"),
            Object(NonMatching, "Rat/LevelAdvancement_G.cpp"),
            Object(NonMatching, "Rat/Ropes_G.cpp"),
            Object(NonMatching, "Rat/Mission_Mutli_Rope.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupYesNo.cpp"),
            Object(NonMatching, "Rat/CreaturesDashStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Collect.cpp"),
            Object(NonMatching, "Rat/BaseAgent_G.cpp"),
            Object(NonMatching, "Rat/UnLock_G.cpp"),
            Object(NonMatching, "Rat/CollectAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Chase.cpp"),
            Object(NonMatching, "Rat/IT_SOUND_G.CPP"),
            Object(NonMatching, "Rat/ScriptManagerRtcScript_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookinCakeInterface.cpp"),
            Object(NonMatching, "Rat/PhysicWorld_G.cpp"),
            Object(NonMatching, "Rat/IT_DYNOBJ_G.cpp"),
            Object(NonMatching, "Rat/MissionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/ScriptManager_G.cpp"),
            Object(NonMatching, "Rat/PermanentDraw.cpp"),
            Object(NonMatching, "Rat/CreatureVehiculeStates_G.cpp"),
            Object(NonMatching, "Rat/CreaturesWallClimbStates.cpp"),
            Object(NonMatching, "Rat/Dialogs_Pause.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Collect_Interface.cpp"),
            Object(NonMatching, "Rat/EndMissionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/VibrationKeyframers_G.cpp"),
            Object(NonMatching, "Rat/HumanHideVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_MisssionEnd.cpp"),
            Object(NonMatching, "Rat/UserCommand_G.cpp"),
            Object(NonMatching, "Rat/CreaturesJumpStates_G.cpp"),
            Object(NonMatching, "Rat/MenuTools.cpp"),
            Object(NonMatching, "Rat/SaveVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/GroupTriggerZone_G.cpp"),
            Object(NonMatching, "Rat/BaseInGameDatas_Text_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Race.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Crepe.cpp"),
            Object(NonMatching, "Rat/InGameFX_G.cpp"),
            Object(NonMatching, "Rat/CheckpointVolAgent_G.cpp"),
            Object(NonMatching, "Rat/MissionManager_G.cpp"),
            Object(NonMatching, "Rat/CreaturesEnemiesStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_ShootTarget.cpp"),
            Object(NonMatching, "Rat/RtcScripted_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Ball_Interface.cpp"),
            Object(NonMatching, "Rat/NodeVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoup.cpp"),
            Object(NonMatching, "Rat/Mission_Mutli_Race_Interface.cpp"),
            Object(NonMatching, "Rat/MemoryCardMgr_G.cpp"),
            Object(NonMatching, "Rat/PersoLight_G.cpp"),
            Object(NonMatching, "Rat/ConditionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/IT_BallWalkMove_G.cpp"),
            Object(NonMatching, "Rat/CameraChase.cpp"),
            Object(NonMatching, "Rat/IT_LinkObj.cpp"),
            Object(NonMatching, "Rat/BaseInGameItems_G.cpp"),
            Object(NonMatching, "Rat/CreaturePointJump.cpp"),
            Object(NonMatching, "Rat/Dialogs_Common.cpp"),
            Object(NonMatching, "Rat/CameraTools.cpp"),
            Object(NonMatching, "Rat/FXVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Switch.cpp"),
            Object(NonMatching, "Rat/Game_ParticleMgr_G.cpp"),
            Object(NonMatching, "Rat/ProGounrMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureSticky.cpp"),
            Object(NonMatching, "Rat/IT_Condition.cpp"),
            Object(NonMatching, "Rat/IT_Break.cpp"),
            Object(NonMatching, "Rat/CreaturesMove_G.cpp"),
            Object(NonMatching, "Rat/Dialog_MC_Base.cpp"),
            Object(NonMatching, "Rat/Mission_Semaphore.cpp"),
            Object(NonMatching, "Rat/CreatureShootTarget.cpp"),
            Object(NonMatching, "Rat/GuardMove_G.cpp"),
            Object(NonMatching, "Rat/Player_G.cpp"),
            Object(NonMatching, "Rat/ScriptManagerEngine_G.cpp"),
            Object(NonMatching, "Rat/IT_BallMove_G.cpp"),
            Object(NonMatching, "Rat/ZoneVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuStyle.cpp"),
            Object(NonMatching, "Rat/LangDefine.cpp"),
            Object(NonMatching, "Rat/GroupAgent_G.cpp"),
            Object(NonMatching, "Rat/GusteauAgent.cpp"),
            Object(NonMatching, "Rat/CreaturesGrabStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Rope_Interface.cpp"),
            Object(NonMatching, "Rat/LevelData_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupInterface.cpp"),
            Object(NonMatching, "Rat/Mission_CookingLinguini.cpp"),
            Object(NonMatching, "Rat/DetectVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Glissade.cpp"),
            Object(NonMatching, "Rat/DialogVoices.cpp"),
            Object(NonMatching, "Rat/GameLogicAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuParser.cpp"),
            Object(NonMatching, "Rat/RtcScriptFunctions_G.cpp"),
            Object(NonMatching, "Rat/PaddleChecker_G.cpp"),
            Object(NonMatching, "Rat/CreaturesMachineCommands_G.cpp"),
            Object(NonMatching, "Rat/IT_Bumper.cpp"),
            Object(NonMatching, "Rat/ImpactVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/MusicManager_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_FishInterface.cpp"),
            Object(NonMatching, "Rat/Mission_Tutorial.cpp"),
            Object(NonMatching, "Rat/MainGame_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayerGarfield_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_MainMenu.cpp"),
            Object(NonMatching, "Rat/CreatureCarry.cpp"),
            Object(NonMatching, "Rat/LevelAgent_G.cpp"),
            Object(NonMatching, "Rat/GlobalInGameDatas_G.cpp"),
            Object(NonMatching, "Rat/Purchase.cpp"),
            Object(NonMatching, "Rat/Creatures_G.cpp"),
            Object(NonMatching, "Rat/Dialog_G.cpp"),
            Object(NonMatching, "Rat/CreatureRatBeamRun.cpp"),
            Object(NonMatching, "Rat/CreatureRatRope.cpp"),
            Object(NonMatching, "Rat/Mission_CookingPlate.cpp"),
            Object(NonMatching, "Rat/V_RaftMove.cpp"),
            Object(NonMatching, "Rat/LevelMenu_G.cpp"),
            Object(NonMatching, "Rat/IT_Ball_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Ball.cpp"),
            Object(NonMatching, "Rat/Mission_CookingCake.cpp"),
            Object(NonMatching, "Rat/Mission_TimeCount.cpp"),
            Object(NonMatching, "Rat/CameraFog_G.cpp"),
            Object(NonMatching, "Rat/PhysicAgt_G.cpp"),
            Object(NonMatching, "Rat/Mission_PushButtonInterface.cpp"),
            Object(NonMatching, "Rat/Mission_PushButton.cpp"),
            Object(NonMatching, "Rat/Enemies_G.cpp"),
            Object(NonMatching, "Rat/Button_G.cpp"),
            Object(NonMatching, "Rat/IT_Stone_G.cpp"),
            Object(NonMatching, "Rat/GroupMove_G.cpp"),
            Object(NonMatching, "Rat/IT_BreakMove.cpp"),
            Object(NonMatching, "Rat/Mission_PushLift.cpp"),
            Object(NonMatching, "Rat/CreaturesCommands_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayer_Draw_G.cpp"),
            Object(NonMatching, "Rat/V_Raft.cpp"),
            Object(NonMatching, "Rat/IT_Carrying.cpp"),
            Object(NonMatching, "Rat/InputDef_G.cpp"),
            Object(NonMatching, "Rat/Mission_Global.cpp"),
            Object(NonMatching, "Rat/CameraRTC.cpp"),
            Object(NonMatching, "Rat/Mission_Raft.cpp"),
            Object(NonMatching, "Rat/IT_LinkObjMove.cpp"),
            Object(NonMatching, "Rat/IT_CollectMove_G.cpp"),
            Object(NonMatching, "Rat/PointJump_G.cpp"),
            Object(NonMatching, "Rat/LogicLevel.cpp"),
            Object(NonMatching, "Rat/MissionInfo_G.cpp"),
            Object(NonMatching, "Rat/Mission_PreLinguiniMaking.cpp"),
            Object(NonMatching, "Rat/CreatureOtherStates_G.cpp"),
            Object(NonMatching, "Rat/CreatureFlying.cpp"),
            Object(NonMatching, "Rat/VolumeDelayedStartMove_G.cpp"),
            Object(NonMatching, "Rat/Mission_Container.cpp"),
            Object(NonMatching, "Rat/Mission_GlissadeInterface.cpp"),
        ],
    },
    {
        "lib": "bink",
        "mw_version": "ProDG/3.5",
        "cflags": cflags_bink_base,
        "progress_category": "bink",  # str | List[str]
        "objects": [
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/ngc/binkngc.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/ngc/ngcsnd.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/binkread.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/ngc/ngcfile.c"),
            Object(NonMatching, "3rdParty/shared/memory/ngc/radmem.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/yuv.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/binkacd.c"),
            Object(NonMatching, "3rdParty/shared/time/ngc/radcb.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/expand.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/popmal.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/decode/ppc/ppcyuy2.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/fft.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/dct.c"),
            Object(NonMatching, "3rdParty/bink/src/sdk/bitplane.c"),
        ],
    }
]


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["3rdParty/dolphin/os/OSFatal.c"]
    return objects

# Uncomment to enable the link order callback.
config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("rat", "Ratatouille Code"),
    ProgressCategory("game", "Game Code"),
    ProgressCategory("engine", "Engine Code"),
    ProgressCategory("libgc", "LibGC Code"),
    ProgressCategory("sdk", "SDK Code"),
    ProgressCategory("bink", "Bink Code"),
]
config.progress_each_module = args.verbose

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress and write progress.json
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
