#ifndef _ABC_MESSAGE_ENGINE_H_
#define _ABC_MESSAGE_ENGINE_H_

typedef int abc_message;

// Engine Messages
enum {
    msg_no_message = 0,                             // 0x00 - MonopolyX360SUB.xdb
    msg_anim_note_track_first = 1,                  // 0x01 - JIMMY.ELF
    msg_skel_collide = 2,                           // 0x02 - MonopolyX360SUB.xdb
    msg_anim_loop = 3,                              // 0x03 - MonopolyX360SUB.xdb
    msg_anim_nosmooth = 4,                          // 0x04 - MonopolyX360SUB.xdb
    msg_anim_smoothratio = 5,                       // 0x05 - MonopolyX360SUB.xdb
    msg_anim_node_collide = 6,                      // 0x06 - MonopolyX360SUB.xdb
    msg_anim_node_uncollide = 7,                    // 0x07 - MonopolyX360SUB.xdb
    msg_anim_node_getorient = 8,                    // 0x08 - MonopolyX360SUB.xdb
    msg_anim_orient = 9,                            // 0x09 - MonopolyX360SUB.xdb
    msg_anim_noorient = 10,                         // 0x0A - MonopolyX360SUB.xdb
    msg_anim_action = 11,                           // 0x0B - MonopolyX360SUB.xdb
    msg_anim_loop_start = 12,                       // 0x0C - MonopolyX360SUB.xdb
    msg_anim_loop_end = 13,                         // 0x0D - MonopolyX360SUB.xdb
    msg_anim_nodynamic = 14,                        // 0x0E - MonopolyX360SUB.xdb
    msg_anim_dynamic = 15,                          // 0x0F - MonopolyX360SUB.xdb
    msg_anim_material_color = 16,                   // 0x10 - MonopolyX360SUB.xdb
    msg_anim_activate_animated_object = 17,         // 0x11 - AnimFrame_Z::InitNoteTrack (Light_Z, HFog_Z or Omni_Z)
    msg_anim_deactivate_animated_object = 18,       // 0x12 - AnimFrame_Z::InitNoteTrack (Light_Z, HFog_Z or Omni_Z)
    msg_anim_hide = 19,                             // 0x13 - AnimFrame_Z::InitNoteTrack
    msg_anim_unhide = 20,                           // 0x14 - AnimFrame_Z::InitNoteTrack
    msg_anim_reset = 21,                            // 0x15 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_replay = 22,                           // 0x16 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_pause = 23,                            // 0x17 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_resume = 24,                           // 0x18 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_play_dialog = 25,                      // 0x19 - Maybe not rtc exclusive RtcScriptAgent_G::GlobalTrackMessage maybe subtitles
    msg_anim_stop_dialog = 26,                      // 0x1A - MonopolyX360SUB.xdb
    msg_anim_load_dialog = 27,                      // 0x1B - Maybe not rtc exclusive RtcScriptAgent_G::GlobalTrackMessage maybe subtitles
    msg_anim_unknown_skel_collide = 28,             // 0x1C - MonopolyX360SUB.xdb
    msg_anim_hit_skel_collide = 29,                 // 0x1D - Player_G::CheckHit
    msg_anim_particles_efx = 30,                    // 0x1E - Creatures_G::ParticlesEfx, RtcScriptAgent_G::RtcParticlesEfx
    msg_anim_particles_efx_pause = 31,              // 0x1F - Creatures_G::ParticlesEfxPause
    msg_anim_particles_efx_reset = 32,              // 0x20 - Creatures_G::ParticlesEfxReset
    msg_anim_play_sound = 33,                       // 0x21 - AnimFrame_Z::UpdateNoteTrack
    msg_rsc_note_track_first = msg_anim_play_sound, // 0x21 - MonopolyX360SUB.xdb
    msg_anim_stop_sound = 34,                       // 0x22 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_hide_node = 35,                        // 0x23 - AnimFrame_Z::InitNoteTrack hide a node passed by param
    msg_anim_unhide_node = 36,                      // 0x24 - AnimFrame_Z::InitNoteTrack unhide a node passed by param
    msg_anim_set_anim = 37,                         // 0x25 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_start_material_anim = 38,              // 0x26 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_stop_material_anim = 39,               // 0x27 - AnimFrame_Z::UpdateNoteTrack
    msg_anim_pause_material_anim = 40,              // 0x28 - MonopolyX360SUB.xdb DOES NOTHING
    msg_anim_note_track_end = 41,                   // 0x29 - JIMMY.ELF
    msg_rsc_note_track_end = 42,                    // 0x2A - MonopolyX360SUB.xdb
    msg_rtc_started = 43,                           // 0x2B - MonopolyX360SUB.xdb / CameraAgent_Z::CameraAgentSuspend
    msg_rtc_ended = 44,                             // 0x2C - MonopolyX360SUB.xdb RtcAgent_Z::RtcEnd
    msg_rtc_changecamera = 45,                      // 0x2D - MonopolyX360SUB.xdb
    msg_rtc_restore_trs = 46,                       // 0x2E - MonopolyX360SUB.xdb
    msg_rtc_mark = 47,                              // 0x2F - MonopolyX360SUB.xdb
    msg_anim_dlighton = 48,                         // 0x30 - MonopolyX360SUB.xdb
    msg_anim_dlightoff = 49,                        // 0x31 - MonopolyX360SUB.xdb
    msg_rtc_no_trs = 50,                            // 0x32 - MonopolyX360SUB.xdb
    msg_goto_length = 51,                           // 0x33 - MonopolyX360SUB.xdb
    msg_goto_curlength = 52,                        // 0x34 - MonopolyX360SUB.xdb
    msg_goto_2nd_vertex = 53,                       // 0x35 - MonopolyX360SUB.xdb
    msg_goto_end = 54,                              // 0x36 - MonopolyX360SUB.xdb
    msg_volume_in = 55,                             // 0x37 - MonopolyX360SUB.xdb
    msg_volume_out = 56,                            // 0x38 - MonopolyX360SUB.xdb
    msg_volume_stay = 57,                           // 0x39 - MonopolyX360SUB.xdb
    msg_volume_anim_reset = 58,                     // 0x3A - VolumeAgent_Z::VolumeAnimReset
    msg_anim_stopallsound = 59,                     // 0x3B - MonopolyX360SUB.xdb
    msg_anim_node_stopalldialog = 60,               // 0x3C - MonopolyX360SUB.xdb
    msg_carry_begin = 61,                           // 0x3D - MonopolyX360SUB.xdb
    msg_carry_end = 62,                             // 0x3E - MonopolyX360SUB.xdb
    msg_held_begin = 63,                            // 0x3F - MonopolyX360SUB.xdb
    msg_held_end = 64,                              // 0x40 - MonopolyX360SUB.xdb
    msg_thrown_begin = 65,                          // 0x41 - MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_thrown_end = 66,                            // 0x42 - MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_target_hit = 67,                            // 0x43 - MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_target_miss = 68,                           // 0x44 - MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_lod_collide = 69,                           // 0x45 - MonopolyX360SUB.xdb
    msg_decor_collide = 70,                         // 0x46 - MonopolyX360SUB.xdb
    msg_thrown_lod_collide = 71,                    // 0x47 - MonopolyX360SUB.xdb
    msg_thrown_decor_collide = 72,                  // 0x48 - MonopolyX360SUB.xdb
    msg_restore_collide = 73,                       // 0x49 - MonopolyX360SUB.xdb
    msg_sequenced_collide = 74,                     // 0x4A - Creatures_G::Contact
    msg_skin_act_begin = 75,                        // 0x4B - SkinAgent_Z::Act
    msg_skin_act_end = 76,                          // 0x4C - SkinAgent_Z::Act
    msg_bumper = 77,                                // 0x4D - JIMMY.ELF - ITS ONE OF THE TWO
    msg_father_unlinked = 77,                       // 0x4D - JIMMY.ELF - ITS ONE OF THE TWO
    msg_camera_capture_patch_start = 78,            // 0x4E - MonopolyX360SUB.xdb
    msg_camera_capture_frame_start = 79,            // 0x4F - MonopolyX360SUB.xdb
    msg_camera_capture_texture_start = 80,          // 0x50 - MonopolyX360SUB.xdb
    msg_camera_capture_end = 81,                    // 0x51 - MonopolyX360SUB.xdb
    msg_camera_capture_param_1 = 82,                // 0x52 - MonopolyX360SUB.xdb
    msg_camera_capture_param_2 = 83,                // 0x53 - MonopolyX360SUB.xdb
    msg_camera_capture_param_3 = 84,                // 0x54 - MonopolyX360SUB.xdb
    msg_camera_reset_focus = 85,                    // 0x55 - MonopolyX360SUB.xdb
    msg_stream_end = 86,                            // 0x56 - StreamAgent_Z::StreamEnd
    msg_stream_error_init = 87,                     // 0x57 - MonopolyX360SUB.xdb
    msg_stream_error = 88,                          // 0x58 - StreamAgent_Z::StreamError
    msg_stream_error_trayopen = 89,                 // 0x59 - MonopolyX360SUB.xdb
    msg_stream_resumed = 90,                        // 0x5A - MonopolyX360SUB.xdb
    msg_stream_resume_possible = 91,                // 0x5B - MonopolyX360SUB.xdb
    msg_stream_abort = 92,                          // 0x5C - MonopolyX360SUB.xdb
    msg_stream_aborted = 93,                        // 0x5D - MonopolyX360SUB.xdb
    msg_game_activated = 94,                        // 0x5E - GameLogicAgent_G::ActivateGame !!IMPORTANT, MenuLogicAgent_G::ActivateGame
    msg_game_deactivated = 95,                      // 0x5F - GameLogicAgent_G::DectivateGame
    msg_game_reseted = 96,                          // 0x60 - GameLogicAgent_G::GameReseted
    msg_anim_framelink = 97,                        // 0x61 - CameraAgent_G::CameraAgentQuartier
    msg_anim_frameunlink = 98,                      // 0x62 - MonopolyX360SUB.xdb
    msg_avirer = 99,                                // 0x63 - MonopolyX360SUB.xdb
    msg_occluder_on = 100,                          // 0x64 - MonopolyX360SUB.xdb
    msg_occluder_off = 101,                         // 0x65 - MonopolyX360SUB.xdb
    msg_stencil_on = 102,                           // 0x66 - MonopolyX360SUB.xdb
    msg_stencil_off = 103,                          // 0x67 - MonopolyX360SUB.xdb
    msg_engine_end = 104                            // 0x68 - MonopolyX360SUB.xdb
};

#endif
