#ifndef _ABC_MESSAGE_ENGINE_H_
#define _ABC_MESSAGE_ENGINE_H_

typedef int abc_message;

// Engine Messages
enum {
    msg_no_message = 0,                             // MonopolyX360SUB.xdb
    msg_anim_note_track_first = 1,                  // MonopolyX360SUB.xdb
    msg_skel_collide = 2,                           // MonopolyX360SUB.xdb
    msg_anim_loop = 3,                              // MonopolyX360SUB.xdb
    msg_anim_nosmooth = 4,                          // MonopolyX360SUB.xdb
    msg_anim_smoothratio = 5,                       // MonopolyX360SUB.xdb
    msg_anim_node_collide = 6,                      // MonopolyX360SUB.xdb
    msg_anim_node_uncollide = 7,                    // MonopolyX360SUB.xdb
    msg_anim_node_getorient = 8,                    // MonopolyX360SUB.xdb
    msg_anim_orient = 9,                            // MonopolyX360SUB.xdb
    msg_anim_noorient = 10,                         // MonopolyX360SUB.xdb
    msg_anim_action = 11,                           // MonopolyX360SUB.xdb
    msg_anim_loop_start = 12,                       // MonopolyX360SUB.xdb
    msg_anim_loop_end = 13,                         // MonopolyX360SUB.xdb
    msg_anim_nodynamic = 14,                        // MonopolyX360SUB.xdb
    msg_anim_dynamic = 15,                          // MonopolyX360SUB.xdb
    msg_anim_material_color = 16,                   // MonopolyX360SUB.xdb
    msg_anim_activate_animated_object = 17,         // AnimFrame_Z::InitNoteTrack (Light_Z, HFog_Z or Omni_Z)
    msg_anim_deactivate_animated_object = 18,       // AnimFrame_Z::InitNoteTrack (Light_Z, HFog_Z or Omni_Z)
    msg_anim_hide = 19,                             // AnimFrame_Z::InitNoteTrack
    msg_anim_unhide = 20,                           // AnimFrame_Z::InitNoteTrack
    msg_anim_reset = 21,                            // AnimFrame_Z::UpdateNoteTrack
    msg_anim_replay = 22,                           // AnimFrame_Z::UpdateNoteTrack
    msg_anim_pause = 23,                            // AnimFrame_Z::UpdateNoteTrack
    msg_anim_resume = 24,                           // AnimFrame_Z::UpdateNoteTrack
    msg_anim_play_dialog = 25,                      // Maybe not rtc exclusive RtcScriptAgent_G::GlobalTrackMessage maybe subtitles
    msg_anim_stop_dialog = 26,                      // MonopolyX360SUB.xdb
    msg_anim_load_dialog = 27,                      // Maybe not rtc exclusive RtcScriptAgent_G::GlobalTrackMessage maybe subtitles
    msg_anim_unknown_skel_collide = 28,             // MonopolyX360SUB.xdb
    msg_anim_hit_skel_collide = 29,                 // Player_G::CheckHit
    msg_anim_particles_efx = 30,                    // Creatures_G::ParticlesEfx, RtcScriptAgent_G::RtcParticlesEfx
    msg_anim_particles_efx_pause = 31,              // Creatures_G::ParticlesEfxPause
    msg_anim_particles_efx_reset = 32,              // Creatures_G::ParticlesEfxReset
    msg_anim_play_sound = 33,                       // AnimFrame_Z::UpdateNoteTrack
    msg_rsc_note_track_first = msg_anim_play_sound, // MonopolyX360SUB.xdb
    msg_anim_stop_sound = 34,                       // AnimFrame_Z::UpdateNoteTrack
    msg_anim_hide_node = 35,                        // AnimFrame_Z::InitNoteTrack hide a node passed by param
    msg_anim_unhide_node = 36,                      // AnimFrame_Z::InitNoteTrack unhide a node passed by param
    msg_anim_set_anim = 37,                         // AnimFrame_Z::UpdateNoteTrack
    msg_anim_start_material_anim = 38,              // AnimFrame_Z::UpdateNoteTrack
    msg_anim_stop_material_anim = 39,               // AnimFrame_Z::UpdateNoteTrack
    msg_anim_pause_material_anim = 40,              // MonopolyX360SUB.xdb DOES NOTHING
    msg_rsc_note_track_end = 41,                    // MonopolyX360SUB.xdb
    msg_anim_note_track_end = 42,                   // JIMMY.ELF
    msg_rtc_started = 43,                           // MonopolyX360SUB.xdb / CameraAgent_Z::CameraAgentSuspend
    msg_rtc_ended = 44,                             // MonopolyX360SUB.xdb RtcAgent_Z::RtcEnd
    msg_rtc_changecamera = 45,                      // MonopolyX360SUB.xdb
    msg_rtc_restore_trs = 46,                       // MonopolyX360SUB.xdb
    msg_rtc_mark = 47,                              // MonopolyX360SUB.xdb
    msg_anim_dlighton = 48,                         // MonopolyX360SUB.xdb
    msg_anim_dlightoff = 49,                        // MonopolyX360SUB.xdb
    msg_rtc_no_trs = 50,                            // MonopolyX360SUB.xdb
    msg_goto_length = 51,                           // MonopolyX360SUB.xdb
    msg_goto_curlength = 52,                        // MonopolyX360SUB.xdb
    msg_goto_2nd_vertex = 53,                       // MonopolyX360SUB.xdb
    msg_goto_end = 54,                              // MonopolyX360SUB.xdb
    msg_volume_in = 55,                             // MonopolyX360SUB.xdb
    msg_volume_out = 56,                            // MonopolyX360SUB.xdb
    msg_volume_stay = 57,                           // MonopolyX360SUB.xdb
    msg_volume_anim_reset = 58,                     // VolumeAgent_Z::VolumeAnimReset
    msg_anim_stopallsound = 59,                     // MonopolyX360SUB.xdb
    msg_anim_node_stopalldialog = 60,               // MonopolyX360SUB.xdb
    msg_carry_begin = 61,                           // MonopolyX360SUB.xdb
    msg_carry_end = 62,                             // MonopolyX360SUB.xdb
    msg_held_begin = 63,                            // MonopolyX360SUB.xdb
    msg_held_end = 64,                              // MonopolyX360SUB.xdb
    msg_thrown_begin = 65,                          // MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_thrown_end = 66,                            // MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_target_hit = 67,                            // MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_target_miss = 68,                           // MonopolyX360SUB.xdb / Throwable_Z::CheckThrown
    msg_lod_collide = 69,                           // MonopolyX360SUB.xdb
    msg_decor_collide = 70,                         // MonopolyX360SUB.xdb
    msg_thrown_lod_collide = 71,                    // MonopolyX360SUB.xdb
    msg_thrown_decor_collide = 72,                  // MonopolyX360SUB.xdb
    msg_restore_collide = 73,                       // MonopolyX360SUB.xdb
    msg_sequenced_collide = 74,                     // Creatures_G::Contact
    msg_skin_act_begin = 75,                        // SkinAgent_Z::Act
    msg_skin_act_end = 76,                          // SkinAgent_Z::Act
    msg_bumper = 77,                                // JIMMY.ELF - ITS ONE OF THE TWO
    msg_father_unlinked = 77,                       // JIMMY.ELF - ITS ONE OF THE TWO
    msg_camera_capture_patch_start = 78,            // MonopolyX360SUB.xdb
    msg_camera_capture_frame_start = 79,            // MonopolyX360SUB.xdb
    msg_camera_capture_texture_start = 80,          // MonopolyX360SUB.xdb
    msg_camera_capture_end = 81,                    // MonopolyX360SUB.xdb
    msg_camera_capture_param_1 = 82,                // MonopolyX360SUB.xdb
    msg_camera_capture_param_2 = 83,                // MonopolyX360SUB.xdb
    msg_camera_capture_param_3 = 84,                // MonopolyX360SUB.xdb
    msg_camera_reset_focus = 85,                    // MonopolyX360SUB.xdb
    msg_stream_end = 86,                            // StreamAgent_Z::StreamEnd
    msg_stream_error_init = 87,                     // MonopolyX360SUB.xdb
    msg_stream_error = 88,                          // StreamAgent_Z::StreamError
    msg_stream_error_trayopen = 89,                 // MonopolyX360SUB.xdb
    msg_stream_resumed = 90,                        // StreamAgent_Z::StreamResumed
    msg_stream_resume_possible = 91,                // MonopolyX360SUB.xdb
    msg_stream_abort = 92,                          // MonopolyX360SUB.xdb
    msg_stream_aborted = 93,                        // StreamAgent_Z::StreamAborted
    msg_game_activated = 94,                        // GameLogicAgent_G::ActivateGame !!IMPORTANT, MenuLogicAgent_G::ActivateGame
    msg_game_deactivated = 95,                      // GameLogicAgent_G::DectivateGame
    msg_game_reseted = 96,                          // GameLogicAgent_G::GameReseted
    msg_anim_framelink = 97,                        // CameraAgent_G::CameraAgentQuartier
    msg_anim_frameunlink = 98,                      // MonopolyX360SUB.xdb
    msg_avirer = 99,                                // MonopolyX360SUB.xdb
    msg_occluder_on = 100,                          // MonopolyX360SUB.xdb
    msg_occluder_off = 101,                         // MonopolyX360SUB.xdb
    msg_stencil_on = 102,                           // MonopolyX360SUB.xdb
    msg_stencil_off = 103,                          // MonopolyX360SUB.xdb
    msg_engine_end = 104                            // MonopolyX360SUB.xdb
};

#endif
